In [1]:
import pandas as pd
pd.options.display.max_colwidth = 1000

import sys
sys.path.append("../src")
import ibgedf

In [2]:
dict_mun = ibgedf.utils.get_mun_dict('São Paulo', key='nome')

In [3]:
pes_mun = ibgedf.pesquisa.get_pes_mun()
dict_pes_mun = ibgedf.utils.get_dict(pes_mun[['id','nome']], key='nome')

# Finanças públicas

21

In [4]:
id_pesquisa = dict_pes_mun['Finanças públicas']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [6]:
df['indicador'].unique()

array(['empenhadas', 'Correntes', 'Pessoal e encargos sociais',
       'Outras despesas correntes', 'Capital', 'Investimentos',
       'Amortização da dívida', 'realizadas', 'Obras e instalações',
       'Receitas orçamentárias realizadas', 'Contribuição',
       'Dívida Ativa',
       'Imposto sobre a Propriedade Predial e Territorial - IPTU',
       'Imposto Sobre Serviços - ISS',
       'Imposto sobre Transmissão-Intervivos - ITBI', 'Patrimonial',
       'Taxas', 'União', 'Unidade da Federação', 'Tributárias',
       'Outras receitas correntes',
       'Valor do Fundo de Participação dos Municípios - FPM',
       'Valor do Imposto sobre Operações Financeiras - IOF - OURO - repassado aos Municípios',
       'Valor do Imposto Territorial Rural - ITR'], dtype=object)

# Registro civil

20

In [5]:
id_pesquisa = dict_pes_mun['Registro civil']
id_municipio = dict_mun['Adamantina']

df_des = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [8]:
df_des['indicador'].unique()

array(['Lugar do registro', 'Lugar da ação do processo',
       'Tabelionato de notas', 'Lugar de residência da mãe', 'Hospital',
       'Lugar de residência do falecido', 'Menores de 1 ano'],
      dtype=object)

# Censo

23

In [4]:
id_pesquisa = dict_pes_mun['Censo']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [5]:
df['indicador'].unique()

array(['Coletivos', 'Com morador', 'Sem morador', 'Ocupados',
       'Com entrevista realizada', 'Sem entrevista realizada',
       'Não ocupados', 'Uso ocasional', 'Vagos', 'Recenseados',
       'População residente', 'Masculino', 'Menos de 1 ano de idade',
       '1 a 4 anos de idade', '5 a 9 anos', '10 a 14 anos de idade',
       '15 a 19 anos', '20 a 24 anos', '25 a 29 anos', '30 a 34 anos',
       '35 a 39 anos', '40 a 44 anos', '45 a 49 anos', '50 a 54 anos',
       '55 a 59 anos', '60 a 64 anos', '65 a 69 anos', '70 a 74 anos',
       '75 a 79 anos', '80 a 84 anos', '85 a 89 anos', '90 a 94 anos',
       '95 a 99 anos', '100 anos ou mais', 'Urbana', 'Rural', 'Feminino',
       'Média de moradores em domicílios particulares ocupados',
       'Sem rendimento', 'Até 1/4 de salário mínimo',
       'Mais de 1/4 a 1/2 salário mínimo',
       'Mais de 1/2 a 1 salário mínimo', 'Mais de 1 a 2 salários mínimos',
       'Mais de 2 a 3 salários mínimos', 'Mais de 3 a 5 salários mínimos',
       'Mais de 5 salários mínimos', 'Automóvel para uso particular',
       'Geladeira', 'Máquina de lavar roupa', 'Microcomputador',
       'Com acesso à internet', 'Motocicleta para uso particular',
       'Rádio', 'Televisão', 'Com rendimento domiciliar', 'Tinham',
       'Tinham água canalizada em pelo menos um cômodo',
       'Rede geral de distribuição', 'Outra forma de abastecimento',
       'Tinham água canalizada no terreno ou propriedade', 'Não tinham',
       'Somente telefone celular', 'Somente telefone fixo',
       'Telefone fixo e celular', '1 cômodo', '2 cômodos', '3 cômodos',
       '4 cômodos', '5 cômodos', '6 cômodos', '7 cômodos',
       '8 ou mais cômodos', '1 dormitório', '2 dormitórios',
       '3 dormitórios', '4 ou mais dormitórios',
       'Alvenaria com revestimento', 'Alvenaria sem revestimento',
       'Madeira aparelhada', 'Madeira aproveitada', 'Palha',
       'Taipa revestida', 'Taipa não revestida', 'Outro material',
       'Filhos tidos pelas mulheres de 10 anos ou mais de idade',
       'Nascidos vivos', 'No período de referência de 12 meses',
       'Nascidos mortos', 'Que estavam vivos',
       'Moradores em domicílios particulares permanentes',
       '1 dormitórios', 'Pessoas de 10 anos ou mais de idade',
       'Até 1 salário mínimo', 'Mais de 5 a 10 salários mínimos',
       'Mais de 10 a 20 salários mínimos', 'Mais de 20 salários mínimos',
       'Com rendimento', 'Com rendimento de trabalho',
       'Trabalho principal', 'Diretores e gerentes',
       'Membros das forças armadas, policiais e bombeiros militares',
       'Operadores de instalações e máquinas e montadores',
       'Profissionais das ciências e intelectuais',
       'Técnicos e profissionais de nível médio',
       'Trabalhadores de apoio administrativo',
       'Trabalhadores dos serviços, vendedores dos comércios e mercados',
       'Trabalhadores qualificados da agropecuária, florestais, da caça e da pesca',
       'Trabalhadores qualificados, operários e artesãos da construção, das artes mecânicas e outros ofícios',
       'Ocupações elementares', 'Ocupações mal definidas', 'Até 14 horas',
       '15 a 39 horas', '40 a 44 horas', '45 a 48 horas',
       '49 horas ou mais', 'Conta própria', 'Empregadores', 'Empregados',
       'Com carteira de trabalho assinada',
       'Sem carteira de trabalho assinada',
       'Militares e funcionários públicos estatutários',
       'Trabalhadores na produção para o próprio consumo',
       'Não remunerados',
       'Administração pública, defesa e seguridade social',
       'Agricultura, pecuária, produção florestal, pesca e aquicultura',
       'Água, esgoto, atividades de gestão de resíduos e descontaminação',
       'Alojamento e alimentação', 'Artes, cultura, esporte e recreação',
       'Atividades administrativas e serviços complementares',
       'Atividades financeiras, de seguros e serviços relacionados',
       'Atividades imobiliárias', 'Atividades mal especificadas',
       'Atividades profissionais, científicas e técnicas',
       'Comércio, reparação de veículos automotores e motocicletas',
       'Construção', 'Educação', 'Eletricidade e gás',
       'Indústrias de transformação', 'Indústrias extrativas',
       'Informação e comunicação',
       'Organismos internacionais e outras instituições extraterritoriais',
       'Outras atividades de serviços', 'Saúde humana e serviços sociais',
       'Serviços domésticos', 'Transporte, armazenagem e correio',
       'Casado(a)', 'Desquitado(a) ou separado(a) judicialmente',
       'Divorciado(a)', 'Solteiro(a)', 'Viúvo(a)', 'Viviam em união',
       'Casamento civil e religioso', 'Somente casamento civil',
       'Somente casamento religioso', 'União consensual',
       'Não viviam em união', 'Não viviam, mas já viveram em união',
       'Nunca viveram em união', '10 anos', 'Economicamente ativa',
       'Ocupada', 'Desocupada', 'Não economicamente ativa', '11 anos',
       '12 anos', '13 anos', '14 anos', '70 anos ou mais',
       'Sem instrução e fundamental incompleto',
       'Fundamental completo e médio incompleto',
       'Médio completo e superior incompleto', 'Superior completo',
       'Não determinado', 'Que tiveram filhos',
       'Mais de um município ou país', 'Outro município',
       'País estrangeiro', 'Município de residência',
       'No domicílio de residência', 'Fora do domicílio de residência',
       'Que trabalhavam fora do domicílio e retornavam para seu domicílio diariamente',
       'Até 5 minutos', 'De 6 minutos até meia hora',
       'Mais de meia hora até uma hora',
       'Mais de uma hora até duas horas', 'Mais de duas horas',
       'Frequentavam', '0 a 3 anos', '4 ou 5 anos', '7 a 14 anos',
       '15 a 17 anos', '18 ou 19 anos', '25 anos ou mais', 'Particular',
       'Pública', 'Não frequentavam, mas já frequentaram',
       'Nunca frequentaram', '6 anos', 'Brasileira', 'Nata',
       'Naturalizado', 'Estrangeira', 'Não consegue de modo algum',
       'Grande dificuldade', 'Alguma dificuldade', 'Mental/Intelectual',
       'Sem declaração', 'Nenhuma dessas deficiências',
       'Pelo menos uma das deficiências investigadas', 'Natural',
       'Não natural',
       'Tempo ininterrupto de residência na Unidade da Federação',
       'Menos de 1 ano', '1 a 2 anos', '3 a 5 anos', '6 a 9 anos',
       '10 anos ou mais',
       'Com rendimento de trabalho, ocupada na semana de referência',
       'Até 1/8 de salário mínimo', 'Mais de 1/8 a 1/4 de salário mínimo',
       'Mais de 10 salários mínimos', '0 a 4 anos', '10 a 14 anos',
       '30 a 39 anos', '40 a 49 anos', '50 a 59 anos', '60 a 69 anos',
       'Pessoas que frequentavam escola ou creche',
       'Domicílios particulares permamentes', 'Telefone celular',
       'Telefone fixo', 'Até 1,0 morador',
       'Mais de 1,0 até 2,0 moradores', 'Mais de 2,0 até 3,0 moradores',
       'Mais de 3,0 moradores', 'Sem parede', 'Não ocupada',
       'Não frequentavam', 'Amarela', 'Branca', 'Indígena', 'Parda',
       'Preta', 'Cônjuge ou companheiro(a)', 'Pessoa responsável',
       'Creche', 'Pré-escolar', 'Classe de alfabetização',
       'Alfabetização de jovens e adultos',
       'Regular do ensino fundamental',
       'Educação de jovens e adultos do ensino fundamental',
       'Regular do ensino médio',
       'Educação de jovens e adultos do ensino médio',
       'Superior de graduação', 'Especialização de nível superior',
       'Mestrado', 'Doutorado', '4 anos', '5 anos', '7 a 9 anos',
       '18 e 19 anos', '60 anos ou mais',
       'Não frequentava, mas já frequentou', 'Nunca frequentou',
       'Famílias conviventes residentes em domicílios particulares',
       'Mulher sem cônjuge com filho(s)', 'Casal sem filho(s)',
       'Casal com filhos', 'Casal sem filhos',
       'Mulher sem cônjuge com filhos',
       'Famílias residentes em domicílios particulares', '2 pessoas',
       'Pessoas de 5 anos ou mais de idade que não residiam no município em 31/07/2005',
       'Região Norte', 'Região Nordeste', 'Região Sudeste', 'Região Sul',
       'Região Centro-Oeste', 'Sem especificação', 'Viúvas', 'Solteiras',
       'Divorciadas', 'Desquitadas ou separadas judicialmente', 'Casadas',
       'Que tiveram filhos nascidos vivos', 'Mais de 5 pessoas',
       '5 pessoas', '4 pessoas', '3 pessoas', 'Casal com filho(s)',
       'Até 1/2 salário mínimo', 'Mais de 10 a 15 salários mínimos',
       'Mais de 15 a 20 salários mínimos',
       'Mais de 20 a 30 salários mínimos', 'Mais 30 salários mínimos',
       'Mais de 30 salários mínimos', 'Deficiência mental/intelectual',
       'Sem declaração de deficiência', 'Com nenhuma dessas deficiências',
       'Sem religião', 'Católica apostólica romana', 'Espírita',
       'Evangélica', 'Não determinada', 'Missionária', 'Pentecostal',
       'Umbanda e Candomblé', 'Outras religiosidades',
       'Umbanda e Camdomblé', 'Não sabe',
       'Sem instrução ou fundamental incompleto',
       'Médio completo ou superior incompleto', 'Candomblé',
       'Católica apostólica brasileira', 'Católica ortodoxa',
       'Espiritualista', 'Adventista', 'Batista', 'Congregacional',
       'Luterana', 'Metodista', 'Presbiteriana', 'Comunidade evangélica',
       'Casa da bênção', 'Igreja do Evangelho Quadrangular',
       'O Brasil para cristo', 'Outras', 'Hinduísmo',
       'Não determinada e multiplo pertencimento',
       'Declaração de múltipla religiosidade',
       'Religiosidade não determinada ou mal definida',
       'Testemunhas de Jeová', 'Tradições esotéricas',
       'Tradições indígenas',
       'Outras declarações de religiosidades afrobrasileira',
       'Outras religiões orientais', 'Outras religiosidades cristãs',
       'Domicílios particulares permanentes',
       'Mais de 2 a 5 salários mínimos', 'Umbanda',
       'Igreja messiânica mundial', 'Novas religiões orientais',
       'Judaísmo', 'Islamismo',
       'Igreja de Jesus cristo dos Santos dos últimos dias',
       'Igreja universal do reino de deus', 'Nova vida', 'Maranata',
       'Deus é amor', 'Congregação cristã do Brasil',
       'Assembléia de Deus', 'Evangélica renovada não determinada',
       'Budismo', 'Ateu', 'Agnóstico',
       'Fundamental completo ou médio incompleto',
       'Per capita dos domicílios particulares permanentes',
       '10 a 13 anos', '15 anos', '16 ou 17 anos', 'Contribuinte',
       'Não contribuinte',
       'Pessoas de 10 anos ou mais de idade com rendimento do trabalho principal, ocupada na semana de referência',
       'Contribuinte para instituto de previdência oficial no trabalho principal',
       'Não contribuinte para instituto de previdência oficial no trabalho principal',
       'Trabalhadores domésticos', 'Demais empregados',
       'Sem carteira de trabalho assinada e contribuinte para instituto de previdência oficial no trabalho principal',
       'Sem carteira de trabalho assinada e não contribuinte para instituto de previdência oficial no trabalho principal',
       'Nível de ocupação das pessoas de 10 anos ou mais de idade na semana de referência',
       '10 a 17 anos', '14 ou 15 anos', '18 anos ou mais',
       'Pessoas de 10 a 17 anos de idade', 'Alfabetizado',
       'Não alfabetizado', 'Preta ou parda', '10 a 13 anos de idade',
       'Conta própria e empregadoras', 'Não remunerado',
       'Outras atividades', 'Empregado com carteira de trabalho assinada',
       'Exclusive os empregados com carteira de trabalho assinada',
       'Exclusive as empregadas com carteira de trabalho assinada',
       '16 ou 17 anos de idade', '14 ou 15 anos de idade', 'Alugado',
       'Cedido', 'Por empregador', 'De outra forma', 'Próprio',
       'Já quitado', 'Em aquisição', 'Outra condição', 'Coletado',
       'Por serviço de limpeza', 'Em caçamba de serviço de limpeza',
       'Enterrado (na propriedade)', 'Jogado em rio, lago ou mar',
       'Jogado em terreno baldio ou logradouro',
       'Queimado (na propriedade)', 'Outro destino',
       'Poço ou nascente na propriedade',
       'Poço ou nascente fora da propriedade', 'Rede geral',
       'Água da chuva armazenada em cisterna',
       'Água da chuva armazenada de outra forma', 'Carro-pipa',
       'Poço ou nascente na aldeia', 'Poço ou nascente fora da aldeia',
       'Rio, açude, lago ou igarapé', 'Outra',
       'Uso exclusivo do domicílio', 'Rede geral de esgoto ou pluvial',
       'Fossa séptica', 'Fossa rudimentar', 'Vala', 'Rio, lago ou mar',
       'Outro', 'Tinham sanitário', 'Não tinham banheiro nem sanitário',
       'De companhia distribuidora', 'Com medidor',
       'Comum a mais de um domicílio', 'Uso exclusivo', 'Sem medidor',
       'De outra fonte', '1 morador', '2 moradores', '3 moradores',
       '4 moradores', '5 moradores', '6 moradores', '7 moradores',
       '8 moradores', '9 moradores', '10 moradores',
       '11 moradores ou mais', 'Apartamento', 'Casa',
       'Casa de vila ou em condomínio',
       'Habitação em casa de cômodo, cortiço ou cabeça de porco',
       'Oca ou maloca', '15 anos ou mais', '80 a 89 anos', '90 a 99 anos',
       'Sem responsabilidade compartilhada',
       'Com responsabilidade compartilhada',
       'Cônjuge ou companheiro(a) de sexo diferente',
       'Cônjuge ou companheiro(a) do mesmo sexo', 'Agregado(a)',
       'Avô ou avó', 'Bisneto(a)', 'Enteado(a)', 'Filho(a)',
       'Filiação da pessoa responsável e do cônjuge',
       'Filiação somente da pessoa responsável', 'Genro ou nora',
       'Irmão ou irmã', 'Neto(a)', 'Pai, mãe, padrasto ou madrasta',
       'Sogro(a)', 'Outro parente', 'Convivente',
       'Empregado(a) doméstico(a)', 'Individual em domicílio coletivo',
       'Parente do(a) empregado(a) doméstico(a)', 'Pensionista',
       'Menos de 1 mês', '1 mês', '2 meses', '3 meses', '4 meses',
       '5 meses', '6 meses', '7 meses', '8 meses', '9 meses', '10 meses',
       '11 meses', '1 ano', '2 anos', '3 anos', '7 anos', '8 anos',
       '9 anos', '16 anos', '17 anos', '18 anos', '19 anos', '20 anos',
       '21 anos', '22 anos', '23 anos', '24 anos', 'Adequado',
       'Inadequado', 'Semi-adequado', '15 a 24 anos', 'Taxa percentual',
       '25 a 39 anos', '40 a 59 anos', 'Permanente', 'Até R$ 70,00',
       'Até 1/4 salário mínimo', 'Até 60% da mediana',
       '0 a 5 anos de idade', '6 a 14 anos de idade',
       'Com responsável ou cônjuge analfabeto',
       'Valor médio do rendimento mensal total nominal',
       'Masculino/Feminino',
       'Valor mediano do rendimento mensal total nominal', 'Valor médio',
       '1º quartil', '2º quartil ou  mediana', '3º quartil',
       '2º quartil ou mediana', 'Ano 2000', '24 a 59 anos', 'Ano 2010',
       'Unidades domésticas', 'Responsável e cônjuge',
       'Único responsável', 'Com mais de 1 responsável',
       'Responsável e cônjuge com filhos e/ou outros parentes', 'Outros',
       'Nuclear', 'Homem com filho(s)', 'Mulher com filho(s)',
       'Estendida', 'Casal com filho(s) e outro(s) parente(s)',
       'Casal sem filho(s) e outro(s) parente(s)',
       'Homem com filho(s) e outro(s) parente(s)',
       'Mulher com filho(s) e outro(s) parente(s)', 'Composta',
       'Casal com filho(s), com não parente(s) e com ou sem outro(s) parente(s)',
       'Casal sem filho(s), com não parente(s) e com ou sem outro(s) parente(s)',
       'Homem com filho(s), com não parente(s) e com ou sem outro(s) parente(s)',
       'Mulher com filho(s), com não parente(s) e com ou sem outro(s) parente(s)',
       'Domicílios', 'Coletivo', 'Edificações em construção', 'Endereços',
       'Com coordenadas coletadas', 'Com identificação de número',
       'Sem numeração', 'Estabelecimentos', 'Existe', 'Não existe',
       'Mais de 2 salários mínimos', 'Não tinham banheiro ou sanitário',
       'Tinham banheiro ou sanitário', 'Outras finalidades', 'Saúde',
       'Ensino', 'Agropecuário'], dtype=object)

In [6]:
df[df['indicador']=='Artes, cultura, esporte e recreação'].head()

,localidade,id,ano,valor,classe,indicador,nota,posicao,unidade,unidade.classe,unidade.id,unidade.multiplicador
178,350010,26237,2010,52,I,"Artes, cultura, esporte e recreação",[],2.4.3.1.3.4.5,NaN,N,pessoas,1.0
591,350010,24062,2010,99999999999992,I,"Artes, cultura, esporte e recreação",[],4.1.1.1.1.5,NaN,N,pessoas,1.0
614,350010,24087,2010,99999999999992,I,"Artes, cultura, esporte e recreação",[],4.1.1.2.1.5,NaN,N,pessoas,1.0
637,350010,24112,2010,99999999999992,I,"Artes, cultura, esporte e recreação",[],4.1.1.3.1.5,NaN,N,pessoas,1.0
660,350010,24137,2010,52,I,"Artes, cultura, esporte e recreação",[],4.1.1.4.1.5,NaN,N,pessoas,1.0

In [7]:
ind = ibgedf.pesquisa.get_unnested_ind(id_pesquisa)

In [11]:
ind[ind['posicao'].str.contains('^4\.1', regex=True)]

,classe,id,indicador,nota,posicao,unidade,unidade.classe,unidade.id,unidade.multiplicador
40,None,24054,"Pessoas de 10 anos ou mais de idade, ocupadas na semana de referência",[],4.1,NaN,NaN,NaN,NaN
143,None,24055,Local de exercício do trabalho principal,[],4.1.1,NaN,NaN,NaN,NaN
436,I,24056,Mais de um município ou país,[],4.1.1.1,NaN,N,pessoas,1.0
437,I,24081,Outro município,[],4.1.1.2,NaN,N,pessoas,1.0
438,I,24106,País estrangeiro,[],4.1.1.3,NaN,N,pessoas,1.0
439,I,24131,Município de residência,[],4.1.1.4,NaN,N,pessoas,1.0
1049,None,24057,Seção de atividade,[],4.1.1.1.1,NaN,NaN,NaN,NaN
1050,None,24082,Seção de atividade,[],4.1.1.2.1,NaN,NaN,NaN,NaN
1051,None,24107,Seção de atividade,[],4.1.1.3.1,NaN,NaN,NaN,NaN
1052,None,24132,Seção de atividade,[],4.1.1.4.1,NaN,NaN,NaN,NaN
1921,I,24058,"Administração pública, defesa e seguridade social",[],4.1.1.1.1.1,NaN,N,pessoas,1.0
1922,I,24059,"Agricultura, pecuária, produção florestal, pesca e aquicultura",[],4.1.1.1.1.2,NaN,N,pessoas,1.0
1923,I,24060,"Água, esgoto, atividades de gestão de resíduos e descontaminação",[],4.1.1.1.1.3,NaN,N,pessoas,1.0
1924,I,24061,Alojamento e alimentação,[],4.1.1.1.1.4,NaN,N,pessoas,1.0
1925,I,24062,"Artes, cultura, esporte e recreação",[],4.1.1.1.1.5,NaN,N,pessoas,1.0
1926,I,24063,Atividades administrativas e serviços complementares,[],4.1.1.1.1.6,NaN,N,pessoas,1.0
1927,I,24064,"Atividades financeiras, de seguros e serviços relacionados",[],4.1.1.1.1.7,NaN,N,pessoas,1.0
1928,I,24065,Atividades imobiliárias,[],4.1.1.1.1.8,NaN,N,pessoas,1.0
1929,I,24066,Atividades mal especificadas,[],4.1.1.1.1.9,NaN,N,pessoas,1.0
1930,I,24067,"Atividades profissionais, científicas e técnicas",[],4.1.1.1.1.10,NaN,N,pessoas,1.0
1931,I,24068,"Comércio, reparação de veículos automotores e motocicletas",[],4.1.1.1.1.11,NaN,N,pessoas,1.0
1932,I,24069,Construção,[],4.1.1.1.1.12,NaN,N,pessoas,1.0
1933,I,24070,Educação,[],4.1.1.1.1.13,NaN,N,pessoas,1.0
1934,I,24071,Eletricidade e gás,[],4.1.1.1.1.14,NaN,N,pessoas,1.0
1935,I,24072,Indústrias de transformação,[],4.1.1.1.1.15,NaN,N,pessoas,1.0
1936,I,24073,Indústrias extrativas,[],4.1.1.1.1.16,NaN,N,pessoas,1.0
1937,I,24074,Informação e comunicação,[],4.1.1.1.1.17,NaN,N,pessoas,1.0
1938,I,24075,Organismos internacionais e outras instituições extraterritoriais,[],4.1.1.1.1.18,NaN,N,pessoas,1.0
1939,I,24077,Saúde humana e serviços sociais,[],4.1.1.1.1.19,NaN,N,pessoas,1.0
1940,I,24078,Serviços domésticos,[],4.1.1.1.1.20,NaN,N,pessoas,1.0
...,...,...,...,...,...,...,...,...,...
1979,I,24122,Indústrias de transformação,[],4.1.1.3.1.15,NaN,N,pessoas,1.0
1980,I,24123,Indústrias extrativas,[],4.1.1.3.1.16,NaN,N,pessoas,1.0
1981,I,24124,Informação e comunicação,[],4.1.1.3.1.17,NaN,N,pessoas,1.0
1982,I,24125,Organismos internacionais e outras instituições extraterritoriais,[],4.1.1.3.1.18,NaN,N,pessoas,1.0
1983,I,24127,Saúde humana e serviços sociais,[],4.1.1.3.1.19,NaN,N,pessoas,1.0
1984,I,24128,Serviços domésticos,[],4.1.1.3.1.20,NaN,N,pessoas,1.0
1985,I,24129,"Transporte, armazenagem e correio",[],4.1.1.3.1.21,NaN,N,pessoas,1.0
1986,I,24126,Outras atividades de serviços,[],4.1.1.3.1.22,NaN,N,pessoas,1.0
1987,I,24133,"Administração pública, defesa e seguridade social",[],4.1.1.4.1.1,NaN,N,pessoas,1.0
1988,I,24134,"Agricultura, pecuária, produção florestal, pesca e aquicultura",[],4.1.1.4.1.2,NaN,N,pessoas,1.0
1989,I,24135,"Água, esgoto, atividades de gestão de resíduos e descontaminação",[],4.1.1.4.1.3,NaN,N,pessoas,1.0
1990,I,24136,Alojamento e alimentação,[],4.1.1.4.1.4,NaN,N,pessoas,1.0
1991,I,24137,"Artes, cultura, esporte e recreação",[],4.1.1.4.1.5,NaN,N,pessoas,1.0
1992,I,24138,Atividades administrativas e serviços complementares,[],4.1.1.4.1.6,NaN,N,pessoas,1.0
1993,I,24139,"Atividades financeiras, de seguros e serviços relacionados",[],4.1.1.4.1.7,NaN,N,pessoas,1.0
1994,I,24140,Atividades imobiliárias,[],4.1.1.4.1.8,NaN,N,pessoas,1.0
1995,I,24141,Atividades mal especificadas,[],4.1.1.4.1.9,NaN,N,pessoas,1.0
1996,I,24142,"Atividades profissionais, científicas e técnicas",[],4.1.1.4.1.10,NaN,N,pessoas,1.0
1997,I,24143,"Comércio, reparação de veículos automotores e motocicletas",[],4.1.1.4.1.11,NaN,N,pessoas,1.0
1998,I,24144,Construção,[],4.1.1.4.1.12,NaN,N,pessoas,1.0
1999,I,24145,Educação,[],4.1.1.4.1.13,NaN,N,pessoas,1.0
2000,I,24146,Eletricidade e gás,[],4.1.1.4.1.14,NaN,N,pessoas,1.0
2001,I,24147,Indústrias de transformação,[],4.1.1.4.1.15,NaN,N,pessoas,1.0
2002,I,24148,Indústrias extrativas,[],4.1.1.4.1.16,NaN,N,pessoas,1.0
2003,I,24149,Informação e comunicação,[],4.1.1.4.1.17,NaN,N,pessoas,1.0
2004,I,24150,Organismos internacionais e outras instituições extraterritoriais,[],4.1.1.4.1.18,NaN,N,pessoas,1.0
2005,I,24152,Saúde humana e serviços sociais,[],4.1.1.4.1.19,NaN,N,pessoas,1.0
2006,I,24153,Serviços domésticos,[],4.1.1.4.1.20,NaN,N,pessoas,1.0
2007,I,24154,"Transporte, armazenagem e correio",[],4.1.1.4.1.21,NaN,N,pessoas,1.0
2008,I,24151,Outras atividades de serviços,[],4.1.1.4.1.22,NaN,N,pessoas,1.0

# Sinopse municipal

33

In [12]:
id_pesquisa = dict_pes_mun['Sinopse municipal']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [13]:
df.head()

,localidade,id,ano,valor,classe,indicador,nota,posicao,unidade
0,350010,29171,2010,None,I,População estimada,"[{'periodo': '2019', 'notas': ['Para ""dúvidas e contestações"" [clique aqui](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html)']}]",1,"{'id': 'pessoas', 'classe': 'N', 'multiplicador': 1}"
1,350010,29171,2015,None,I,População estimada,"[{'periodo': '2019', 'notas': ['Para ""dúvidas e contestações"" [clique aqui](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html)']}]",1,"{'id': 'pessoas', 'classe': 'N', 'multiplicador': 1}"
2,350010,29171,2016,None,I,População estimada,"[{'periodo': '2019', 'notas': ['Para ""dúvidas e contestações"" [clique aqui](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html)']}]",1,"{'id': 'pessoas', 'classe': 'N', 'multiplicador': 1}"
3,350010,29171,2017,35139,I,População estimada,"[{'periodo': '2019', 'notas': ['Para ""dúvidas e contestações"" [clique aqui](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html)']}]",1,"{'id': 'pessoas', 'classe': 'N', 'multiplicador': 1}"
4,350010,29171,2018,35023,I,População estimada,"[{'periodo': '2019', 'notas': ['Para ""dúvidas e contestações"" [clique aqui](https://www.ibge.gov.br/estatisticas/sociais/populacao/9103-estimativas-de-populacao.html)']}]",1,"{'id': 'pessoas', 'classe': 'N', 'multiplicador': 1}"

In [15]:
df['indicador'].unique()

array(['População estimada', 'População', 'Área da unidade territorial',
       'Densidade demográfica', 'Código do Município', 'Prefeito',
       'Gentílico'], dtype=object)

# Índice de Desenvolvimento Humano

37

In [17]:
id_pesquisa = dict_pes_mun['Índice de Desenvolvimento Humano']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [18]:
df['indicador'].unique()

array(['IDH'], dtype=object)

In [19]:
df.head()

  localidade     id   ano  valor classe indicador nota posicao
0     350010  30255  1991  0.592      I       IDH   []       1
1     350010  30255  2000  0.721      I       IDH   []       1
2     350010  30255  2010  0.790      I       IDH   []       1

# Produto Interno Bruto dos Municípios

38

In [20]:
id_pesquisa = dict_pes_mun['Produto Interno Bruto dos Municípios']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [21]:
df['indicador'].unique()

array(['Série revisada', 'Série retropolada', 'Série encerrada',
       'Agropecuária', 'Indústria',
       'Serviços - Exclusive Administração, defesa, educação e saúde públicas e seguridade social',
       'Administração, defesa, educação e saúde públicas e seguridade social',
       'Serviços'], dtype=object)

In [23]:
df.dropna(how='any').head()

,localidade,id,ano,valor,classe,indicador,nota,posicao,unidade.classe,unidade.id,unidade.multiplicador
11,350010,46997,2010,639091,I,Série revisada,[],1.1,$,R$,1000.0
12,350010,46997,2011,683689,I,Série revisada,[],1.1,$,R$,1000.0
13,350010,46997,2012,743684,I,Série revisada,[],1.1,$,R$,1000.0
14,350010,46997,2013,815579,I,Série revisada,[],1.1,$,R$,1000.0
15,350010,46997,2014,862888.67,I,Série revisada,[],1.1,$,R$,1000.0

# Panorama municipal

10058

In [39]:
id_pesquisa = dict_pes_mun['Panorama municipal']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [31]:
df['indicador'].unique()

array(['Arborização de vias públicas', 'Esgotamento sanitário adequado',
       'Urbanização de vias públicas', 'PIB per capita',
       'Percentual das receitas oriundas de fontes externas',
       'Anos iniciais do ensino fundamental',
       'Anos finais do ensino fundamental', '6 a 14 anos de idade',
       'Internações por diarreia', 'Média', 'População ocupada',
       'Até ½ salário mínimo', 'Salário médio mensal'], dtype=object)

In [32]:
df.dropna(how='any').head()

,localidade,id,ano,valor,classe,indicador,nota,posicao,unidade.classe,unidade.id,unidade.multiplicador
0,350010,60029,2010,99.3,I,Arborização de vias públicas,"[{'periodo': '2010', 'notas': ['[domicílios urbanos em face de quadra com arborização/domicílios urbanos totais] x100']}]",1.1,N,%,1.0
7,350010,60030,2010,95.8,I,Esgotamento sanitário adequado,"[{'periodo': '2010', 'notas': ['[população total residente nos domicílios particulares permanentes com esgotamento sanitário do tipo rede geral e fossa séptica / População total residente nos domicílios particulares permanentes] x 100']}]",1.2,N,%,1.0
14,350010,60031,2010,17.9,I,Urbanização de vias públicas,"[{'periodo': '2010', 'notas': ['[domicílios urbanos em face de quadra com boca de lobo e pavimentação e meio-fio e calçada/domicílios urbanos totais] x 100']}]",1.3,N,%,1.0
24,350010,60047,2014,25229.43,I,PIB per capita,[],2.1,$,R$,1.0
32,350010,60048,2015,55.4,I,Percentual das receitas oriundas de fontes externas,[],2.2,N,%,1.0

# MUNIC - Perfil dos Municípios Brasileiros

1

In [38]:
id_pesquisa = dict_pes_mun['MUNIC - Perfil dos Municípios Brasileiros']
id_municipio = dict_mun['Adamantina']

df = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

Exception: Bad Request for url	https://servicodados.ibge.gov.br/api/v1/pesquisas/1/indicadores/0