In [1]:
import pandas as pd
pd.options.display.max_colwidth = 1000

import importlib

In [2]:
import sys
sys.path.append("../src")

In [3]:
import ibgedf

# IBGE DataFrames

Explorando a API do IBGE através de DataFrames

Por enquanto o código implementado suporta consulta à API de Pesquisas com foco em Municípios

In [4]:
dict_mun = ibgedf.utils.get_mun_dict('São Paulo', key='nome')

In [5]:
dict_mun['Adamantina']

3500105

## Pesquisas disponíveis

Dicionário de id/pesquisa que foram realizadas em municípios (algumas pesquisas são aplicadas exclusivamente a estados, por exemplo)

In [6]:
pes_mun = ibgedf.pesquisa.get_pes_mun()

In [7]:
dict_pes_mun = ibgedf.utils.get_dict(pes_mun[['id','nome']], key='nome')

In [8]:
for k,v in dict_pes_mun.items():
    print('{}:\n{}\n\n'.format(k,v))

MUNIC - Perfil dos Municípios Brasileiros:
1


Censo escolar - sinopse:
13


Produção Agrícola - Lavoura Temporária:
14


Produção Agrícola - Lavoura Permanente:
15


Extração vegetal e Silvicultura:
16


Morbidade:
17


Pecuária:
18


Cadastro Central de Empresas:
19


Registro civil:
20


Finanças públicas:
21


Frota de veículos:
22


Censo:
23


Censo Agropecuário:
24


Instituições financeiras:
29


Pesquisa nacional de saneamento básico:
30


Produção agrícola - Cereais, leguminosas e oleaginosas:
31


Serviços de saúde:
32


Sinopse municipal:
33


Pesquisa de serviços de hospedagem:
34


Fundações privadas e associações sem fins lucrativos:
35


Mapa de pobreza e desigualdade:
36


Índice de Desenvolvimento Humano:
37


Produto Interno Bruto dos Municípios:
38


Taxa de mortalidade infantil:
39


Índice de Desenvolvimento da Educação Básica:
40


Notificações de dengue registradas:
42


Panorama municipal:
10058


MUNIC - Suplemento Finanças públicas:
10075


MUNIC - Suplemento Esporte:
10077


MUNIC - Suplemento Meio Ambiente:
10078


MUNIC - Suplemento Assistência Social:
10079


MUNIC - Suplemento Inclusão Produtiva:
10084


MUNIC - Suplemento Cultura:
10085


MUNIC - Suplemento  Aspectos gerais da gestão da política de saneamento básico:
10087

## Consultando resultados de pesquisas

### Pesquisa 36

Mapa de pobreza e desigualdade

In [9]:
id_pesquisa = dict_pes_mun['Mapa de pobreza e desigualdade']
id_municipio = dict_mun['Adamantina']

df_des = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

In [10]:
for i in df_des['indicador'].unique():
    print(i)

Incidência da pobreza
Limite inferior
Limite superior
Incidência da pobreza subjetiva
Índice de Gini

In [11]:
df_des.head()

,localidade,id,ano,valor,classe,indicador,nota,posicao,unidade,unidade.classe,unidade.id,unidade.multiplicador
0,350010,30246,2003,18.86,I,Incidência da pobreza,[],1,"{'id': '%', 'classe': 'N', 'multiplicador': 1}",NaN,NaN,NaN
1,350010,30247,2003,13.40,I,Limite inferior,[],1.1,NaN,N,%,1.0
2,350010,30248,2003,24.32,I,Limite superior,[],1.2,NaN,N,%,1.0
3,350010,30249,2003,15.18,I,Incidência da pobreza subjetiva,[],2,"{'id': '%', 'classe': 'N', 'multiplicador': 1}",NaN,NaN,NaN
4,350010,30250,2003,13.38,I,Limite inferior,[],2.1,NaN,N,%,1.0

### Pesquisa 10079

Suplemento Assistência Social

In [12]:
id_pesquisa = 10079
id_municipio = dict_mun['Adamantina']

df_sas = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

Exception: Bad Request for url	https://servicodados.ibge.gov.br/api/v1/pesquisas/10079/indicadores/0

Infelizmente nem todas as pesquisas estão de fato disponíveis através da API.

Caso acredite estar recebendo uma exceção 'Bad Request' como a acima de forma equivocada, envie uma Issue para o repositório do pacote.

### Pesquisa 10084

MUNIC - Suplemento Inclusão Produtiva

In [13]:
id_pesquisa = dict_pes_mun['MUNIC - Suplemento Inclusão Produtiva']
id_municipio = dict_mun['Osasco']

df_sip = ibgedf.pesquisa.get_denorm_res_ind(id_pesquisa, id_municipio)

#### Indicadores disponíveis

In [14]:
for i in df_sip['indicador'].unique():
    print(i)

Estudo setorial e/ou diagnóstico socioeconômico do município realizado entre 2010 e 2014 - existência
Ano do diagnóstico
Órgão responsável pela elaboração
Agricultura
Assistência social
Fazenda
Planejamento
Trabalho
Outro órgão
Especifique
Governo municipal desenvolve ações, programas ou projetos
Desenvolvimento Econômico
Servidores atuando exclusivamente na gestão das ações
Governo municipal desenvolve ações de assistência técnica e extensão rural
Grupos para os quais as ações estão voltadas
Agricultores familiares
Assentados da reforma agrária
Extrativistas e silvicultores
Povos indígenas
Pescadores artesanais e aquicultores familiares
Comunidades remanescentes de quilombos
Outros povos e comunidades tradicionais
Médio e/ou grande produtor rural
Parceiros responsáveis pela implementação
Governo Federal
Governo Estadual
ONGs e entidades do terceiro setor
Sistema S
Universidades, Institutos de ensino técnico e profissional
Entidades de classe de trabalhadores rurais
Entidades de classe patronais rurais
Outros
Governo municipal desenvolve ações de fomento a atividades produtivas
Governo municipal desenvolve ações de incentivo para acesso ao crédito e ao seguro rural
Governo municipal desenvolve ações de aquisição ou empréstimo de tratores e implementos agrícolas
Governo municipal desenvolve ações de doação de sementes ou matrizes de pequenos animais
Governo municipal desenvolve ações de aquisição de alimentos no âmbito do Programa de Aquisição de Alimentos - PAA ou do Programa Nacional de Alimentação Escolar - PNAE
Governo municipal desenvolve ações de aquisição de alimentos para atender a demandas  regulares
Governo municipal desenvolve ações de apoio a transporte, armazenagem, comercialização e distribuição de alimentos
Governo municipal desenvolve ações de assistência técnico-gerencial a empreendimentos coletivos rurais
Governo municipal desenvolve ações de qualificação profissional
Desempregados
Inscritos no Cadastro Único para Programas Sociais
População em situação de rua
Catadores de materiais recicláveis
Governo federal (PRONATEC)
Entidades de classe de trabalhadores
Entidades de classe patronais
Governo municipal desenvolve ações de intermediação de mão-de-obra
Beneficiários do Programa Bolsa Família
Egressos de cursos de capacitação do PRONATEC
Governo federal (Sistema Nacional de Emprego - SINE)
Governo municipal desenvolve ações de mobilização e sensibilização para cursos de qualificação profissional
Entidades de classe, sindicatos patronais e de trabalhadores
Governo municipal ofertou cursos de qualificação ou capacitação profissional oferecidos em 2014
Administração
Agroextrativismo
Alimentação
Arte e cultura
Artesanato
Atividades do comércio e serviços
Construção e reformas
Esporte e lazer
Gestão e empreendimentos
Gráfica
Joalheria
Madeira e móveis
Mecânica de veículos terrestres e aquáticos
Mecânica e manutenção
Metalmecânica
Pecuária
Pesca
Telemática
Têxtil
Transporte
Turismo e hospitalidade
Serviço de alimentação
Vestuários
Reciclagem
Governo municipal desenvolve ações de fomento a empreendimentos individuais urbanos
Egressos de cursos de qualificação profissional
Governo municipal desenvolve ações de fomento a empreendimentos coletivos urbanos
Governo municipal desenvolve ações de assistência técnico-gerencial a empreendimentos individuais urbanos
SEBRAE
Governo municipal desenvolve ações de assistência técnico-gerencial a empreendimentos coletivos urbanos
Governo municipal desenvolve ações de doação de equipamentos ou kit básico para desempenho do trabalho
Governo municipal desenvolve ações para promover o acesso a microcrédito produtivo orientado
Bancos privados
Cooperativas de crédito
Governo municipal desenvolve ações de acesso a crédito por meio do Banco do Povo ou outras organizações congêneres
Governo municipal desenvolve ações de acesso a crédito do Proger urbano
Governo municipal desenvolveu projeto(s) de apoio à comercialização de negócios, cooperativas e empreendimentos solidários
Área de atuação do(s) projeto(s)
Atividade de agricultura urbana
Atividade industrial
Atividade comercial
Atividade de serviços
Outras atividades
Valor aproximado do(s) projeto(s)
Até R$ 50 mil
Mais de R$ 50 mil a R$ 100 mil
Mais de R$ 100 mil a R$ 500 mil
Mais de R$ 500 mil a 1 milhão
Mais de R$ 1 milhão
Tipo(s) de projeto(s) desenvolvido(s):
Desenvolvimento de plano de negócio
Apoio para elaboração de projeto para acesso a fundos privados
Outros projetos
Governo municipal desenvolveu projeto(s) de apoio ao associativismo, cooperativismo e economia solidária
Atividade agrícola, pecuária e extrativa
Código da Unidade da Federação
Código do Municipio
Região
Nome da Unidade da Federação
Sigla da Unidade da Federação
Nome do município
População estimada  2014
Classe de tamanho população
Bancos públicos
Governo municipal desenvolve ações de fomento ao artesanato
Governo municipal desenvolve ações de incubação de empreendimentos
Outros do Sistema S
Serviços pessoais
Serviços domésticos
Saúde
Química e plásticos
Governo municipal desenvolve ações de fomento a empreendimentos coletivos rurais
Apoio para elaboração de projeto para acesso a fundos públicos

#### Consultando indicador específico

In [15]:
df_sip[df_sip['indicador'] == 'População em situação de rua'].head()

,localidade,id,ano,valor,classe,indicador,nota,posicao
198,353440,72132,2014,Sim,I,População em situação de rua,[],3.1.1.1.4
265,353440,72218,2014,Sim,I,População em situação de rua,[],4.1.1.1.6
282,353440,72238,2014,Sim,I,População em situação de rua,[],4.2.1.1.6
297,353440,72258,2014,Sim,I,População em situação de rua,[],4.3.1.1.6
313,353440,72279,2014,Sim,I,População em situação de rua,[],4.4.1.1.6

#### Explorando indicadores

In [16]:
ind = ibgedf.pesquisa.get_unnested_ind(id_pesquisa)

In [17]:
ind[ind['indicador']=='População em situação de rua']

    classe     id                     indicador nota    posicao
303      I  72132  População em situação de rua   []  3.1.1.1.4
327      I  72166  População em situação de rua   []  3.3.1.1.4
370      I  72218  População em situação de rua   []  4.1.1.1.6
385      I  72238  População em situação de rua   []  4.2.1.1.6
400      I  72258  População em situação de rua   []  4.3.1.1.6
416      I  72279  População em situação de rua   []  4.4.1.1.6
431      I  72299  População em situação de rua   []  4.5.1.1.6
446      I  72319  População em situação de rua   []  4.6.1.1.6
461      I  72339  População em situação de rua   []  4.7.1.1.6
476      I  72360  População em situação de rua   []  5.1.1.1.6
494      I  72383  População em situação de rua   []  5.2.1.1.6
509      I  72403  População em situação de rua   []  5.3.1.1.6

In [18]:
ind[ind['posicao'].isin(['3','4','5'])]

,classe,id,indicador,nota,posicao
2,None,72125,Qualificação profissional e intermediação de mão de obra,[],3
3,None,72209,EMPREENDIMENTOS URBANOS,[],4
4,None,72351,"CRÉDITO, MICROCRÉDITO E SEGURO",[],5

In [19]:
ind[ind['indicador'] == 'Arte e cultura ']

    classe     id        indicador nota    posicao
339      I  72183  Arte e cultura    []  3.4.1.1.5

In [20]:
ind[ind['posicao'].str.contains('^3.4', regex=True)]

,classe,id,indicador,nota,posicao
22,None,72176,Cursos de qualificação ou capacitação profissional,[],3.4
60,I,72177,Governo municipal ofertou cursos de qualificação ou capacitação profissional oferecidos em 2014,[],3.4.1
108,None,72178,Áreas temáticas:,[],3.4.1.1
335,I,72179,Administração,[],3.4.1.1.1
336,I,72180,Agricultura,[],3.4.1.1.2
337,I,72181,Agroextrativismo,[],3.4.1.1.3
338,I,72182,Alimentação,[],3.4.1.1.4
339,I,72183,Arte e cultura,[],3.4.1.1.5
340,I,72184,Artesanato,[],3.4.1.1.6
341,I,72185,Atividades do comércio e serviços,[],3.4.1.1.7
342,I,72186,Construção e reformas,[],3.4.1.1.8
343,I,72187,Esporte e lazer,[],3.4.1.1.9
344,I,72188,Gestão e empreendimentos,[],3.4.1.1.10
345,I,72189,Gráfica,[],3.4.1.1.11
346,I,72190,Joalheria,[],3.4.1.1.12
347,I,72191,Madeira e móveis,[],3.4.1.1.13
348,I,72192,Mecânica de veículos terrestres e aquáticos,[],3.4.1.1.14
349,I,72193,Mecânica e manutenção,[],3.4.1.1.15
350,I,72194,Metalmecânica,[],3.4.1.1.16
351,I,72195,Pecuária,[],3.4.1.1.17
352,I,72196,Pesca,[],3.4.1.1.18
353,I,72197,Química e plásticos,[],3.4.1.1.19
354,I,72198,Saúde,[],3.4.1.1.20
355,I,72199,Serviços domésticos,[],3.4.1.1.21
356,I,72200,Serviços pessoais,[],3.4.1.1.22
357,I,72201,Telemática,[],3.4.1.1.23
358,I,72202,Têxtil,[],3.4.1.1.24
359,I,72203,Transporte,[],3.4.1.1.25
360,I,72204,Turismo e hospitalidade,[],3.4.1.1.26
361,I,72205,Serviço de alimentação,[],3.4.1.1.27
362,I,72206,Vestuários,[],3.4.1.1.28
363,I,72207,Reciclagem,"[{'periodo': '2014', 'notas': ['Reciclagem de resíduos sólidos e óleos/gorduras residuais.']}]",3.4.1.1.29
364,I,72208,Outros,[],3.4.1.1.30